'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@example/stencil-lib-react";
import type { Components } from "@example/stencil-lib/dist/components";
import { ScopedChild as ScopedChildElement } from "@example/stencil-lib/dist/components/scoped-child.js";
import { SlotParent as SlotParentElement } from "@example/stencil-lib/dist/components/slot-parent.js";

export const serializeShadowRoot: SerializeShadowRootOptions = "scoped";

export type ScopedChildEvents = NonNullable<unknown>;

export const ScopedChild: StencilReactComponent<ScopedChildElement, ScopedChildEvents, Components.ScopedChild> = /*@__PURE__*/ createComponent<ScopedChildElement, ScopedChildEvents, Components.ScopedChild>({
    tagName: 'scoped-child',
    properties: {},
    hydrateModule: typeof window === 'undefined' ? (import('@example/stencil-lib/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.ScopedChild as StencilReactComponent<ScopedChildElement, ScopedChildEvents, Components.ScopedChild>,
    serializeShadowRoot
});

export type SlotParentEvents = NonNullable<unknown>;

export const SlotParent: StencilReactComponent<SlotParentElement, SlotParentEvents, Components.SlotParent> = /*@__PURE__*/ createComponent<SlotParentElement, SlotParentEvents, Components.SlotParent>({
    tagName: 'slot-parent',
    properties: {},
    hydrateModule: typeof window === 'undefined' ? (import('@example/stencil-lib/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SlotParent as StencilReactComponent<SlotParentElement, SlotParentEvents, Components.SlotParent>,
    serializeShadowRoot
});
