'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@example/stencil-lib/dist/components";
import { ScopedChild as ScopedChildElement, defineCustomElement as defineScopedChild } from "@example/stencil-lib/dist/components/scoped-child.js";
import { SlotParent as SlotParentElement, defineCustomElement as defineSlotParent } from "@example/stencil-lib/dist/components/slot-parent.js";

export type ScopedChildEvents = NonNullable<unknown>;

export const ScopedChild: StencilReactComponent<ScopedChildElement, ScopedChildEvents, Components.ScopedChild> = /*@__PURE__*/ createComponent<ScopedChildElement, ScopedChildEvents, Components.ScopedChild>({
    tagName: 'scoped-child',
    elementClass: ScopedChildElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ScopedChildEvents,
    defineCustomElement: defineScopedChild
});

export type SlotParentEvents = NonNullable<unknown>;

export const SlotParent: StencilReactComponent<SlotParentElement, SlotParentEvents, Components.SlotParent> = /*@__PURE__*/ createComponent<SlotParentElement, SlotParentEvents, Components.SlotParent>({
    tagName: 'slot-parent',
    elementClass: SlotParentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SlotParentEvents,
    defineCustomElement: defineSlotParent
});
