/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScopedChild {
    }
    interface SlotParent {
    }
}
declare global {
    interface HTMLScopedChildElement extends Components.ScopedChild, HTMLStencilElement {
    }
    var HTMLScopedChildElement: {
        prototype: HTMLScopedChildElement;
        new (): HTMLScopedChildElement;
    };
    interface HTMLSlotParentElement extends Components.SlotParent, HTMLStencilElement {
    }
    var HTMLSlotParentElement: {
        prototype: HTMLSlotParentElement;
        new (): HTMLSlotParentElement;
    };
    interface HTMLElementTagNameMap {
        "scoped-child": HTMLScopedChildElement;
        "slot-parent": HTMLSlotParentElement;
    }
}
declare namespace LocalJSX {
    interface ScopedChild {
    }
    interface SlotParent {
    }
    interface IntrinsicElements {
        "scoped-child": ScopedChild;
        "slot-parent": SlotParent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scoped-child": LocalJSX.IntrinsicElements["scoped-child"] & JSXBase.HTMLAttributes<HTMLScopedChildElement>;
            "slot-parent": LocalJSX.IntrinsicElements["slot-parent"] & JSXBase.HTMLAttributes<HTMLSlotParentElement>;
        }
    }
}
